### PR TITLE
Add outpost2 app

### PR DESCRIPTION
**Pull request by Brett208**
Do you want the Outpost2App files to be added to the Outpost2DLL project so they compile as well?

Other next step is actually adding the Outpost2App headers to Outpost2App.h.

### CODE REVIEW

**Comment by Brett208** [comment]
Only 1800 code additions. I'm guessing GitHub is desiring to change all the line endings as the files are renamed again.

**Review by DanRStevens — APPROVED** [review]
Changes look good.

I was just thinking, the cause of the automatic line end conversions are probably the result of the Git settings we choose. I remember we had a discussion on this a while back. I had suggested turning off automatic conversions done by Git, though that proved impractical on Windows with MSVC. I don't think there is a warn option for when it does it. Maybe we can find a tool to give us advance warning of non-standard line endings. Or perhaps this needs to become part of the SVN -> Git conversion process.

----

I had a couple of additions to make after reviewing. Things kind of snowballed from there. I suppose now you'll want to review my code. :wink:

**Comment by Brett208** [comment]
Added Outpost2App headers to Outpost2DLL project. Compiled okay. Updated a Yukon Trail locally to use this branch for Outpost2DLL. Everything compiled fine again.

Not sure how else to test. Guess I'm happy merging.

The fact that we are redefining objects in OP2Internal that exist in Outpost2DLL and redefining objects in Outpost2App that exist in OP2Internal seems incorrect to me. 

-Brett

**Comment by DanRStevens** [comment]
There should be no current redefinitions. They were edited out or replaced with forward declarations instead.

**Pull request merged**
